# Generated by Django 4.0.5 on 2022-06-17 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teste',
            field=models.ManyToManyField(blank=True, related_name='teste', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='media/profile_pictures/default.png', upload_to='media/profile_pictures'),
        ),
    ]
